### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by SkyZH** [SkyZH/raytracer#1]
![image](https://user-images.githubusercontent.com/4198311/43998236-610af656-9e23-11e8-90cb-32998e3d93d8.png)

**Comment by SkyZH** [comment]
![image](https://user-images.githubusercontent.com/4198311/43998239-9751cc58-9e23-11e8-802b-43cd248512cf.png)

**Comment by SkyZH** [comment]
![image](https://user-images.githubusercontent.com/4198311/43998298-e55e0802-9e24-11e8-8c52-c33910d4cae5.png)

**Comment by SkyZH** [comment]
![image](https://user-images.githubusercontent.com/4198311/43998466-ea89acec-9e28-11e8-96d0-1e1307b3e806.png)

**Comment by SkyZH** [comment]
![image](https://user-images.githubusercontent.com/4198311/44003127-7f702fe6-9e80-11e8-88fc-9d2ed95ac5d0.png)

**Comment by SkyZH** [comment]
![image](https://user-images.githubusercontent.com/4198311/44022411-174c9cac-9f1a-11e8-9292-8ba8fabed5b5.png)

**Comment by SkyZH** [comment]
![complex_scene_1](https://user-images.githubusercontent.com/4198311/51087070-38a7f300-1789-11e9-9b84-d96f9bb1d556.png)

**Comment by SkyZH** [comment]
![complex_scene_2](https://user-images.githubusercontent.com/4198311/51087490-17e29c00-178f-11e9-88fc-996f642859d0.png)

**Comment by SkyZH** [comment]
![legacy_scene_texture](https://user-images.githubusercontent.com/4198311/51223750-1b884580-197e-11e9-93c8-f4c8779d1958.png)

**Comment by SkyZH** [comment]
![simple_scene_perlin_noise](https://user-images.githubusercontent.com/4198311/51226964-f9e28a80-198c-11e9-95ee-374e3598adc2.png)

**Comment by SkyZH** [comment]
![legacy_scene_light](https://user-images.githubusercontent.com/4198311/51253655-e9a4cc80-19d9-11e9-9ea4-ddec4e4208eb.png)

**Comment by SkyZH** [comment]
![cornell_box](https://user-images.githubusercontent.com/4198311/51380265-4922e980-1b4c-11e9-85e2-1d5430a47b22.png)

**Comment by skyzh** [comment]
![cornell](https://user-images.githubusercontent.com/4198311/69005795-ee237400-0961-11ea-82dd-2345c9aecabd.png)

**Comment by skyzh** [comment]
![cornell](https://user-images.githubusercontent.com/4198311/69006131-ec5baf80-0965-11ea-8b1a-f9905f357196.png)

**Comment by skyzh** [comment]
![cornell](https://user-images.githubusercontent.com/4198311/69006152-275de300-0966-11ea-892e-3ba2d475ed40.png)
